<?php

/*
Plugin Name: Text Analyzer
Plugin URI: https://github.com/xulegaspi/text-analyzer
Description: A brief description of the Plugin.
Version: 1.0
Author: Xurxo Legaspi
License: GPLv3
*/

/* Set the version number of the plugin. */
define( 'TextAnalyzer_version', 3.15 );

/* Set the path to the root directory */
define( 'ABSPATH', dirname(__FILE__) );
//$path = get_home_path();

/* Set constant path to the plugin directory. */
define( 'TextAnalyzer_path', plugin_dir_path( __FILE__ ) );

/* Set constant url to the plugin directory. */
define( 'TextAnalyzer_URL', plugin_dir_url( __FILE__ ) );

/* Set the constant path to the plugin's template directory. */
define( 'TEMPLATES', TextAnalyzer_path . trailingslashit( 'templates' ), true );

//require_once(TextAnalyzer_path . 'xml_parser.php');

/* Runs when plugin is activated */
register_activation_hook(__FILE__, 'hello_world_install');

/* Runs when plugin is deactivated */
register_deactivation_hook(__FILE__, 'hello_world_remove');

function hello_world_install() {

    /* Creates new database field */
    add_option('hello_world_data', 'Default', '', 'yes');
}

function hello_world_remove() {
    /* Deletes the database field */
    delete_option('hello_world_data');
}

add_action('init', 'hello_world');
function hello_world() {
    echo "Hello world yuuuuujuuuu";
}

add_action('admin_menu', 'my_plugin_menu');

function my_plugin_menu() {

    add_options_page( 'My Plugin Options', 'Text Analyzer', 'manage_options', 'text-analyzer-settings', 'my_plugin_options' );
	add_management_page('TextAnalyzer', 'TextAnalyzer', 'manage_options', 'text-analyzer', 'text_analyzer_page');

}

function my_plugin_options() {
    if ( !current_user_can( 'manage_options' ) )  {
        wp_die( __( 'You do not have sufficient permissions to access this page.' ) );
    }

	// Check that the nonce is valid, and the user can edit this post.
	//if (
	//	isset( $_POST['my_file_upload_nonce'], $_POST['post_id'] )
	//	&& wp_verify_nonce( $_POST['my_image_upload_nonce'], 'my_image_upload' )
	//	&& current_user_can( 'edit_post', $_POST['post_id'] )
	//) {
		// The nonce was valid and the user has the capabilities, it is safe to continue.

		// These files need to be included as dependencies when on the front end.
		//require_once( ABSPATH . 'wp-admin/includes/image.php' );
		//require_once( ABSPATH . 'wp-admin/includes/file.php' );
		//require_once( ABSPATH . 'wp-admin/includes/media.php' );

		// Let WordPress handle the upload.
		// Remember, 'my_image_upload' is the name of our file input in our form above.
		/*$attachment_id = media_handle_upload( 'my_file_upload', $_POST['post_id'] );

		if ( is_wp_error( $attachment_id ) ) {
			// There was an error uploading the image.
			//echo "GOOD MORNING";
			echo is_wp_error($attachment_id);
		} else {
			// The image was uploaded successfully!
			echo "THE IMAGE IS HERE!!!";
		}*/

	$uploadedfile = $_FILES['file'];

	$upload_overrides = array( 'test_form' => false );

	$movefile = wp_handle_upload( $uploadedfile, $upload_overrides );

	if ( $movefile && !isset( $movefile['error'] ) ) {
		echo "File is valid, and was successfully uploaded.\n";
		var_dump( $movefile );
	} else {
		/**
		 * Error generated by _wp_handle_upload()
		 * @see _wp_handle_upload() in wp-admin/includes/file.php
		 */
		//echo $uploadedfile['name'];
		echo $movefile['error'];
	}

	//} else {

		// The security check failed, maybe show the user an error.
//		echo "GOOD NIGHT";
//	}

    $response = file_get_contents(TEMPLATES . "settings.html");
    echo $response;
/*
	echo "<p>Choose the file.</p>";
	echo '<form id="featured_upload" method="POST" action="#" enctype="multipart/form-data">';
	echo '<input type="file" name="my_file" id="my_file_upload" multiple="false" />';
	echo '<input type="hidden" name="post_id" id="post_id" value="55" />';
	wp_nonce_field( 'my_file_upload', 'my_file_upload_nonce' );
	echo '<input id="submit_my_file" name="submit_my_file" type="submit" value="Upload" />';
	echo '</form>';
*/
}

function text_analyzer_page() {
	if ( !current_user_can( 'manage_options' ) )  {
		wp_die( __( 'You do not have sufficient permissions to access this page.' ) );
	}

	$response = file_get_contents(TEMPLATES . "text-analyzer.html");
	echo $response;


}


